## async/await

### 重要知识点总结

- async函数是什么？ 是Generator函数的语法糖

- async函数对Generator函数的改进
1. 内置执行器。Generator 函数的执行必须靠执行器，所以才有了co模块，而async函数自带执行器。
2. 更好的语义。async和await，比起星号和yield，语义更清楚了。async表示函数里有异步操作，await表示紧跟在后面的表达式需要等待结果。
3. 更广的适用性。co模块约定，yield命令后面只能是 Thunk 函数或 Promise 对象，而async函数的await命令后面，可以是 Promise 对象和原始类型的值（但这时会自动转成立即 resolved 的 Promise 对象）
4. 返回值是 Promise。async函数的返回值是 Promise 对象。你可以用then方法指定下一步的操作。

- async 难点是错误处理机制

### async

1. async函数返回一个 Promise 对象。

2. async函数内部return语句返回的值，会成为then方法回调函数的参数。
```js
async function f() {
  return 'hello world';
}

f().then(v => console.log(v))
// "hello world"
```
3. async函数内部抛出错误，会导致返回的 Promise 对象变为reject状态。抛出的错误对象会被catch方法回调函数接收到。
```js
async function f() {
  throw new Error('出错了');
}

f().then(
  v => console.log('resolve', v),
  e => console.log('reject', e)
)
//reject Error: 出错了

```
4. async函数返回的 Promise 对象，必须等到内部所有await命令后面的 Promise 对象执行完，才会发生状态改变，除非遇到return语句或者抛出错误

```js
async function getTitle(url) {
  let response = await fetch(url);
  let html = await response.text();
  return html.match(/<title>([\s\S]+)<\/title>/i)[1];
}
getTitle('https://tc39.github.io/ecma262/').then(console.log)
// "ECMAScript 2017 Language Specification"
// 只有这三个操作全部完成，才会执行then方法里面的console.log。
```

### await

1. await命令后面是一个 Promise 对象，返回该对象的结果。如果不是 Promise 对象，就直接返回对应的值。
```js
async function f() {
  // 等同于
  // return 123;
  return await 123;
}
f().then(v => console.log(v));
console.log('9999');

/*
  999
  123
*/
```

2. await命令后面是一个thenable对象

```js
// 如何实现休眠效果
function sleep(interval) {
  return new Promise(resolve => {
    setTimeout(resolve, interval);
  })
}

// 用法
async function one2FiveInAsync() {
  for(let i = 1; i <= 5; i++) {
    console.log(i);
    await sleep(1000);
  }
}

one2FiveInAsync();
```

3. await命令后面的 Promise 对象如果变为reject状态，则reject的参数会被catch方法的回调函数接收到。
4. 任何一个await语句后面的 Promise 对象变为reject状态，那么整个async函数都会中断执行。
```js
async function f() {
  await Promise.reject('出错了');
  console.log('0000');
}

f()
.then(v => console.log(v))
.catch(e => console.log(e))
// 出错了
// 0000不会输出
```
5. 修改一个await报错后，后续无法继续执行的问题
```js
async function f() {
  try {
    await Promise.reject('出错了');
  } catch(e) {}
  return await Promise.resolve('hello world');
}

f()
.then(v => console.log(v))
// hello world

// 方法二：
async function f() {
  await Promise.reject('出错了')
    .catch(e => console.log(e));
  return await Promise.resolve('hello world');
}

f()
.then(v => console.log(v))
// 出错了
// hello world
```

6. 接口请求失败后多次重试   await + try...catch
```js
const superagent = require('superagent');
const NUM_RETRIES = 3;

async function test() {
  let i;
  for (i = 0; i < NUM_RETRIES; ++i) {
    try {
      await superagent.get('http://google.com/this-throws-an-error');
      break; // 当请求成功时会执行到break，请求失败会进入catch，然后开始下一轮的循环
    } catch(err) {}
  }
  console.log(i); // 3
}

test();
```

### 使用注意事项

1. await命令后面的Promise对象，运行结果可能是rejected，所以最好把await命令放在try...catch代码块中。 上文有例子

2. 多个await命令后面的异步操作，如果不存在依赖关系，最好让它们同时触发。
```js
// 写法一
let [foo, bar] = await Promise.all([getFoo(), getBar()]);

// 写法二
let fooPromise = getFoo();
let barPromise = getBar();
let foo = await fooPromise;
let bar = await barPromise;

// getFoo和getBar都是同时触发，这样就会缩短程序的执行时间
```

3. await命令只能用在async函数之中，如果用在普通函数，就会报错

4. 在for循环和forEach中使用async存在的差异 [链接文章](StudyJavaScript/JS知识点/异步编程/6. forEach和for循环中的async.md)


5. async 函数可以保留运行堆栈。
```js
const a = () => {
  b().then(() => c());
};
// 上面代码中，函数a内部运行了一个异步任务b()。当b()运行的时候，函数a()不会中断，而是继续执行。等到b()运行结束，可能a()早就运行结束了，b()所在的上下文环境已经消失了。如果b()或c()报错，错误堆栈将不包括a()。

// 现在将这个例子改成async函数。
const a = async () => {
  await b();
  c();
};
// 上面代码中，b()运行的时候，a()是暂停执行，上下文环境都保存着。一旦b()或c()报错，错误堆栈将包括a()。
```





